services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    restart: always
    ports:
      - "8443:8443"
    environment:
      NIFI_WEB_HTTPS_PORT: 8443
      NIFI_WEB_HTTPS_HOST: 0.0.0.0
      SINGLE_USER_CREDENTIALS_USERNAME: admin
      SINGLE_USER_CREDENTIALS_PASSWORD: admin123
    volumes:
      - nifi-data:/opt/nifi/nifi-current/flowfile_repository
      - nifi-data:/opt/nifi/nifi-current/content_repository
      - nifi-data:/opt/nifi/nifi-current/provenance_repository
      - nifi-data:/opt/nifi/nifi-current/database_repository
      - nifi-data:/opt/nifi/nifi-current/state
    user: "1000:1000"
    networks:
      - data-net

networks:
  data-net:
    external: true

volumes:
  nifi-data:
