services:
  jupyter:
    image: jupyter/pyspark-notebook:spark-3.5.0
    container_name: jupyter
    command: start-notebook.sh --NotebookApp.token=''
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - ./project:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    networks:
      - data-net

networks:
  data-net:
    external: true
