services:
  namenode:
    image: apache/hadoop:3
    container_name: namenode
    hostname: namenode
    command: ["/bin/bash", "/start-hdfs.sh"]
    ports:
      - "9870:9870" # NameNode Web UI
      - "9000:9000" # HDFS RPC
    volumes:
      - namenode-data:/hadoop/dfs/name
      - ./hadoop-config:/opt/hadoop/etc/hadoop
      - ./start-hdfs.sh:/start-hdfs.sh
    networks:
      - data-net
    user: root

  datanode:
    image: apache/hadoop:3
    container_name: datanode
    hostname: datanode
    command: ["/bin/bash", "/init-datanode.sh"]
    volumes:
      - datanode-data:/hadoop/dfs/data
      - ./hadoop-config:/opt/hadoop/etc/hadoop
      - ./init-datanode.sh:/init-datanode.sh
    networks:
      - data-net
    user: root

  resourcemanager:
    image: apache/hadoop:3
    container_name: resourcemanager
    hostname: resourcemanager
    command: ["yarn", "resourcemanager"]
    restart: always
    ports:
      - "8088:8088" # YARN Web UI
    networks:
      - data-net

  nodemanager:
    image: apache/hadoop:3
    container_name: nodemanager
    hostname: nodemanager
    command: ["yarn", "nodemanager"]
    restart: always
    networks:
      - data-net

networks:
  data-net:
    external: true

volumes:
  namenode-data:
  datanode-data:
